src/blog/urls.py
from django.urls import path
from .views import create_blog_view, detail_blog_view, edit_blog_view, delete_post_view

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name='create'),
    path('<slug>/', detail_blog_view, name='detail'),
    path('<slug>/edit', edit_blog_view, name='edit'),
    path('<slug>/delete', delete_post_view, name='delete'),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from personal.views import (home_screen_view)
from account.views import (registration_view,
                           logout_view,
                           login_view,
                           account_view,
                           must_authenticate)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name='home'),
    path('blog/', include('blog.urls', 'blog')),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('account/', include('account.urls', 'account')),
    path('must_authenticate/', must_authenticate, name='must_authenticate'),


    # REST FRAMEWORK URLS
    path('api/blog/', include('blog.api.urls','blog_api')),
    path('api/account/', include('account.api.urls','account_api')),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/personal/models.py
from django.db import models

# Create your models here.
"""
PRIORITY = [
    ('L','Low'),
    ('M','Medium'),
    ('H','High')
]

class Question(models.Model):
    title = models.CharField(max_length=60)
    question = models.TextField(max_length=400)
    priority = models.CharField(max_length=1, choices=PRIORITY)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name='The Question'
        verbose_name_plural = 'Peoples Questions'
"""

src/personal/views.py
from django.shortcuts import render
from account.models import Account
from blog.models import BlogPost
from blog.views import get_blog_queryset
from operator import attrgetter
# Create your views here.

def home_screen_view(request):
    context = {}

    query = ''
    if request.GET:
        query = request.GET['q']
        context['query'] = str(query)

    blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse=True)
    context['blog_posts'] = blog_posts
    return render(request,'personal/home.html',context)

src/personal/templates/personal/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">

	@media (max-width: 768px) {
		.right-column{
			margin-left: 0px;
		}
	}

	@media (min-width: 768px) {
		.right-column{
			margin-left: 60px;
		}
	}

	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}

	.left-column{
		padding:0px;
	}

	.right-column{
		padding:0px;
	}
	.lead{
		font-size: 17px;
	}
</style>


<!-- main content -->
<div class="container p-3" style="max-width: 1400px;">
	<div class="row">

		<!-- blog feed -->
		<div class="left-column col-lg-6" style="margin-left: 12px;">

			<!-- Top 'create post' bar -->
			<div class="d-lg-none mb-3">
				<div class="card m-auto d-flex flex-column p-3" style="text-align: center;">
						<img class="center m-auto" src="https://www.flaticon.com/svg/static/icons/svg/609/609803.svg" width="72" height="72">
						<h3 style="margin-top: 10px;">Home</h3>
					<p class="lead m-auto" >Welcome to your home page where you can see various posts posted by you as well as other users.</p>
					<p class="m-auto"><a class="btn btn-lg btn-primary" style="margin-top: 10px;" href="{% url 'blog:create' %}">Create post</a></p>
				</div>
			</div>
			<!-- end Top 'create post' bar -->

			<!-- Blog posts-->
			{% if blog_posts %}
				{% for post in blog_posts %}
					<div class="blog-post-container">
						{% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
					</div>
				{% endfor %}
			{% else %}
				<div class="blog-post-container">
					{% include 'blog/snippets/blog_post_snippet.html' with query=query %}
				</div>
			{% endif %}
			<!-- End Blog posts-->


		</div>
		<!-- end blog feed -->

		<!-- Right 'create post' column  -->
		<div class="right-column col-lg-4 d-lg-flex d-none flex-column">
			<div class="card create-post-bar d-flex flex-column p-3">
				<div class="row">
					<div class="column">
						<img class="img-fluid d-block pb-2" style="margin-left: 20px; margin-bottom: -1px;" src="https://www.flaticon.com/svg/static/icons/svg/609/609803.svg" width="72" height="72">
					</div>
					<div class="column" style="margin-left: 20px;">
						<br>
						<h3>Home</h3>
					</div>
				</div>
				<p class="lead p-1">Welcome to your home page where you can see various posts posted by you as well as other users.</p>
				<a class="btn btn-lg btn-primary btn-block" href="{% url 'blog:create' %}">Create post</a>
			</div>

			<div class="card create-post-bar d-flex flex-column p-3">
				<h3>Search</h3>
				<p class="lead p-1">Search for any posts using keywords.</p>
				<div class="search-bar mt-sm-e mr-2" style="margin-bottom: 10px;">
					<form method="get">
						<input type="text" class="form-control" name="q" id="id_q" placeholder="Search...">
					</form>
				</div>
			</div>
		</div>

		<!-- end Right 'create post' column  -->


	</div>
</div>

<script type="text/javascript">
  document.getElementById('id_q').value = '{{query}}'
</script>

{% endblock content %}