src/account/urls.py
from django.urls import path
from .views import account_view, my_blogs_view

app_name = 'account'

urlpatterns = [
    path('details/', account_view, name='details'),
    path('blogs/', my_blogs_view, name='my_blogs'),
]

src/blog/urls.py
from django.urls import path
from .views import create_blog_view, detail_blog_view, edit_blog_view, delete_post_view

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name='create'),
    path('<slug>/', detail_blog_view, name='detail'),
    path('<slug>/edit', edit_blog_view, name='edit'),
    path('<slug>/delete', delete_post_view, name='delete'),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from personal.views import (home_screen_view)
from account.views import (registration_view,
                           logout_view,
                           login_view,
                           account_view,
                           must_authenticate)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_screen_view, name='home'),
    path('blog/', include('blog.urls', 'blog')),
    path('register/', registration_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('account/', include('account.urls', 'account')),
    path('must_authenticate/', must_authenticate, name='must_authenticate'),


    # REST FRAMEWORK URLS
    path('api/blog/', include('blog.api.urls','blog_api')),
    path('api/account/', include('account.api.urls','account_api')),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),
         name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),
         name='password_change'),

    path('password_reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),

    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/snippets/base_css.html
<style type="text/css">
    body{
    background: #D8D8D8;
    }
</style>

src/templates/snippets/footer.html
<style type="text/css">
    .footer{
        min-height: 60px;
        background: #404040;
    }
</style>

<!--FOOTER-->
<div class="d-flex flex-row align-items-center footer border-top shadow-lg" style="color: #FFFFFF;">
    <p class="m-auto">Full site project | 2020</p>
</div>
<!--END FOOTER-->

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

src/templates/snippets/header.html
<style type="text/css">
html{
      font-size: 14px;
}
@media (min-width: 768px) {
  html {
    font-size: 16px;
  }
}

.container {
  max-width: 960px;
}

.pricing-header {
  max-width: 700px;
}

.card-deck .card {
  min-width: 220px;
}

</style>


<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
        <a href="{% url 'home' %}">
        <img src="https://www.flaticon.com/svg/static/icons/svg/2885/2885645.svg" style="margin-right: 10px;" alt="" width="50" height="50">
        </a>
        {% if user.is_authenticated %}
        <a class="navbar-brand" style="font-size: 23px;" href="{% url 'home' %}">Welcome {{user.username}}!</a>
        {% else %}
        <a class="navbar-brand" style="font-size: 23px;" href="{% url 'home' %}">Welcome to my site!</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" style="margin-left: 20px;" id="navbarsExample07">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" style="font-size: 17px;" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" style="font-size: 17px;" href="">About</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" style="font-size: 17px;" href="{% url 'account:details' %}">Account</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" style="font-size: 17px;" href="http://example.com" id="dropdown07" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Other</a>
              <div class="dropdown-menu" aria-labelledby="dropdown07">
                <a class="dropdown-item" style="font-size: 17px;" href="{% url 'account:my_blogs' %}">My Posts</a>
                <a class="dropdown-item" style="font-size: 17px;" href="{% url 'logout' %}">Logout</a>
              </div>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" style="font-size: 17px;" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" style="font-size: 17px;" href="{% url 'register' %}">Register</a>
            </li>


            {% endif %}
          </ul>
          <form class="form-inline my-2 my-md-0">
            <input class="form-control" type="text" placeholder="Search" aria-label="Search">
          </form>
        </div>
      </div>
    </nav>
</div>

<!--HEADER-->


<!--END HEADER-->